name: Claude Code

on:
  issue_comment:
    types: [created]

jobs:
  claude:
    # Issueのコメントに「@claude」が含まれている場合のみ実行する
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Run Claude
        # 【重要】公式の、対話機能を持つActionを指定します
        uses: anthropics/claude-code-action@beta
